### ISSUE TITLE
Not works C-n keybinding

### ISSUE THREAD

**Issue by emakei** [kaiwk/emacs-keybinding#2]
When I'm try page down, opens new window.
Windows 7 (64-bit)
Firefox: 57.0.4 (64-bit)

**Comment by kaiwk** [comment]
Oops,  I didn't test it on windows, but I think it may conflict with existing keybindings. Since Mac use 'Command-n' to open a new window, Windows may use 'Ctrl-n' to do the same thing.

It's a shame that Firefox 57 or its [WebExtension API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) doesn't give any way to change default keybinding. I have no way to remap the 'Ctrl-n' too.

Here is a [discussion about that on reddit](https://www.reddit.com/r/firefox/comments/77gm9u/changing_default_keyboard_shortcuts_in_firefox_57/).

Hope there will be some progress in the future. Sorry for that.

For your information, I know there is another Add-on for Emacs users: [bebop](https://github.com/kumabook/bebop)
